export const skills = ["HTML",
    "CSS",
    "Javascript",
    "React JS",
    "React Native",
    "Electron JS",
    "MongoDB",
    "PHP",
    "SQL",
    "Python",
    "Accounting",
    "Audit",
    "Income Tax",
    "GST"]